### ISSUE TITLE
Segmentation fault when runing orlis

### ISSUE THREAD

**Issue by metegeral** [presto-osu/orlis-orcis#1]
Orlis throws a segmentation fault when I'm trying to generate a library file from the library binary included in the open source benchmark (Ubuntu 16.04.4):
```
$ ./run.py open_source_benchmarks/all_libraries/xmpcore-5.1.2.jar libraries
[1]    18230 segmentation fault  ./run.py open_source_benchmarks/all_libraries/xmpcore-5.1.2.jar libraries
```

Despite the segfault, a library file is generated. When detecting library classes using these files, the program will throw an exception:
```
$ ./run.py open_source_benchmarks/apks/org.csploit.android_0.apk libraries
terminate called after throwing an instance of 'int'
[1]    19910 abort      ./run.py open_source_benchmarks/apks/org.csploit.android_0.apk libraries
```

Could you give me some instructions about how to fix the issue?

**Comment by xiaoxiaow** [comment]
The problem should come from the Similarity Digest libraries. Did you install all these libraries as mentioned in the Prerequisites? tlsh, fuzzyhashlib and nilsimsa of their python2 version.

**Comment by xiaoxiaow** [comment]
> Orlis throws a segmentation fault when I'm trying to generate a library file from the library binary included in the open source benchmark (Ubuntu 16.04.4):
> 
> ```
> $ ./run.py open_source_benchmarks/all_libraries/xmpcore-5.1.2.jar libraries
> [1]    18230 segmentation fault  ./run.py open_source_benchmarks/all_libraries/xmpcore-5.1.2.jar libraries
> ```
> Despite the segfault, a library file is generated. When detecting library classes using these files, the program will throw an exception:
> 
> ```
> $ ./run.py open_source_benchmarks/apks/org.csploit.android_0.apk libraries
> terminate called after throwing an instance of 'int'
> [1]    19910 abort      ./run.py open_source_benchmarks/apks/org.csploit.android_0.apk libraries
> ```
> Could you give me some instructions about how to fix the issue?

**Comment by metegeral** [comment]
The problem comes from the `fuzzyhashlib.ssdeep` function, which causes segfault on my machine. As a fix, I used the `python-ssdeep` library instead and the problem is gone.

**Comment by xiaoxiaow** [comment]
Good to know that :-)
